### ISSUE TITLE
Search entries always show hard-coded "123 456" OTPs

### ISSUE THREAD

**Issue by Bogatinovski** [bitwarden/authenticator-ios#181] opened 2024-11-03 14:06 UTC
### Steps To Reproduce

1. Click on the "Search" input box
2. When the search popup opens, search for some of your codes
3. All entries in the search result will show "123 456" as an OTP code at all times
4. Wait for the 30 seconds to pass and for the codes to refresh. Even after refresh the codes don't change from "123 456"

This bug is extremely annoying, practically bringing down the usefulness of the app to 0, since I have 100s of entries added to the app and I never scroll to find the right item. I have just migrated from Google Authenticator to Birwarden due to privacy concerns with Google. I have always used the search feature exclusively, so this bug is a deal-breaker for me. I hope it will be resolved soon since I already migrated all my 100+ accounts to Bitwarden Authenticator.

### Expected Result

Search results should have live up-to-date OTP codes

### Actual Result

Search results always have hard-coded value of "123 456" for the OTP codes

### Screenshots or Videos

![IMG_7E9B6D8D5C38-1](https://github.com/user-attachments/assets/2690b2d1-d51d-41eb-9a36-49ff347df27d)

### Build Version

2024.6.1 (45)

### Environment Details

IPhone 13 Pro Max - IOS Version 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment] 2024-11-03 14:54
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: #117 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbw23** 2024-11-03 14:54 UTC
Labels: bug

**Comment by Bogatinovski** [comment] 2024-11-03 14:57
I am getting the same issue on IPhone 13 Pro Max, app version: 2024.6.1 (45)

It appears the PR which fixes this issue has been merged on Sep 25. When will a new app version be published to the Apple Store?
