### ISSUE TITLE
Bug: TOTP codes show placeholder when searching (instead of correct code)

### ISSUE THREAD

**Issue by creativecoder** [bitwarden/authenticator-ios#165] opened 2024-10-08 18:02 UTC
### Steps To Reproduce

1. Open Bitwarden Authenticator for iOS
2. Input text into the search input field to find a specific code

### Expected Result

To see the actual TOTP codes when searching, rather than placeholders

### Actual Result

All of the TOTP codes appear to be hard-coded to "123 456"

### Screenshots or Videos

<img src="https://github.com/user-attachments/assets/cd93f9b5-f733-4499-85b1-49dc84325f94" width="300" alt="screenshot of search input bug showing placeholder codes instead of actual ones" />

### Additional Context

When you have a long list of services, searching helps quickly find the one you're looking for. But with this bug you cannot see the code you need.

### Build Version

2024.6.1 (45)

### Environment Details

- Device iPhone 12 mini
- OS: 17.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-10-08 18:07
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/authenticator-ios/issues/117. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-10-08 18:07 UTC
Labels: bug
