### ISSUE TITLE
When searching, always shows the code 123 456

### ISSUE THREAD

**Issue by b1gsh4d0w** [bitwarden/authenticator-ios#175] opened 2024-10-24 22:29 UTC
### Steps To Reproduce

1. Go to search bar
2. Write down the name of the entry needed
3. When trying to see the code it always shows 123 456

### Expected Result

Should show the actual code, not the default 123 456

### Actual Result

It does not matter what is that you are looking for it always shows the code as 123 456, but the timer is ok

### Build Version

2024.6.1 (45)

### Environment Details

Device: iPhone 12 Pro Max
OS version: 18.0.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-10-25 02:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/authenticator-ios/issues/117

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-10-25 02:50 UTC
Labels: bug
